
namespace Seal.Frontend.WebApp.ClientApp.app.models.autogenerated {

    
    export interface  HopViewModel {
        
        // ID
        id: number;
        // NAME
        name: string;
        // DESCRIPTION
        description: string;
        // CANTRY
        cantry: number;
        // PACKED
        packed: Date;
    }
}