
namespace Seal.Frontend.WebApp.ClientApp.app.models.autogenerated {

    
    export interface  TemplateViewModel {
        
        // ID
        id: number;
        // NAME
        name: string;
        // DESC
        desc: string;
    }
}