import { Injectable } from '@angular/core';
import { Foo, Bar } from '../models';
import { HopViewModel, TemplateViewModel } from '../models/autogenerated';

@Injectable()
export class HopService {

    constructor() { }

    getFoo(): Foo {
        let result = new Foo();

        return result;
    }
    getHop(): HopViewModel {
        let result: HopViewModel = {

            id: 1,
            name: 'Test',
            description: 'Test opis',
            cantry: 12,
            packed: new Date()
        };
        debugger;


        return result;
    }

}
