// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Seal.Backend.DAL.DataContext;
using System;

namespace Seal.Backend.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Seal.Common.Domain.Models.Template.MainTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MainTemplate");
                });

            modelBuilder.Entity("Seal.Common.Domain.Models.Template.RelatedTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MainTemplateId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MainTemplateId");

                    b.ToTable("RelatedTemplate");
                });

            modelBuilder.Entity("Seal.Common.Domain.Models.Template.RelatedTemplate", b =>
                {
                    b.HasOne("Seal.Common.Domain.Models.Template.MainTemplate")
                        .WithMany("RelatedTemplates")
                        .HasForeignKey("MainTemplateId");
                });
#pragma warning restore 612, 618
        }
    }
}
