import { Component } from '@angular/core';
import { HopService } from '../../services/hop.service'
import { HopViewModel } from '../../models/autogenerated'
@Component({
    selector: 'home',
    templateUrl: './home.component.html',
    
})
export class HomeComponent {
    constructor(private _hopService: HopService) {

    }

    getHops() : HopViewModel {
        let result = this._hopService.getHop();

        return result;
    }
}
