import { Component, OnInit } from '@angular/core';
import { HopService } from '../../services/hop.service'
import { HopViewModel } from '../../models/autogenerated'
@Component({
    selector: 'home',
    templateUrl: './home.component.html',
    
})
export class HomeComponent {
    hop: HopViewModel;
    hop2: string; 
    constructor(private _hopService: HopService) {

    }

    getHops() : HopViewModel {
        let result = this._hopService.getHop();

        return result;
    }

    ngOnInit() {
        this.hop2 = "Testowe wywolanie"
        console.error("Pobranie Hopsa");
        this.hop = this.getHops();
    }
}
